Convert games partials to HAML
venuu/video-game-database-ruby pull request #31
Opened 2022-12-15 15:05 UTC by Angel-cuba

2022-12-19 08:10 UTC, jraunio commented
Hola! Do you have a specific question for me regarding this pr?

2022-12-19 08:15 UTC, Angel-cuba commented
It is about the Cypress test, it has failed. I'd need some help to debug this error before this branch is merged.

2022-12-19 08:20 UTC, jraunio commented
Cool! Why do you think the test failed?

2022-12-19 08:39 UTC, jraunio commented
I can give you a tip: the problem is not related to the document structure.

2022-12-19 08:49 UTC, jraunio commented
And this is the line where the failure happens:
```javascript
// Assert that some of the <h1> to <h6> tags that might be on the page
// contain the expected heading
cy.findAllByRole('heading').should('contain', 'Filter by genre and/or year')
```

2022-12-19 09:15 UTC, Angel-cuba commented
It's fixed now!

2022-12-19 10:27 UTC, valscion commented on app/views/games/_filters.html.haml
> +        = link_to "All", root_path
This needs some additional code to make the link same as earlier. For reference, this was how the link was made with ERB:

https://github.com/venuu/video-game-database-ruby/blob/7755427861cf0b821a255b236a87ad8d40674094/app/views/games/_filters.html.erb#L5

The custom class definition is missing here.

2022-12-19 10:27 UTC, valscion commented on app/views/games/_filters.html.haml
> +                = link_to genre.name, root_path(:genre=> genre.id)
This needs some additional code to make the link same as earlier. This was how it used to be:

https://github.com/venuu/video-game-database-ruby/blob/7755427861cf0b821a255b236a87ad8d40674094/app/views/games/_filters.html.erb#L8

Things that are missing are:

* `year` query parameter
* Custom classes

2022-12-19 10:27 UTC, valscion commented on app/views/games/_filters.html.haml
> +        %h3 Filter by genre and/or year
There used to be only one `h3` on the `_filters` partial, now we have two. Let's fix it so that there is only one, and the one that is there is the one on row 2, immediately after `<div class="filters">` opens with the `.filters` HAML code.

2022-12-19 10:27 UTC, valscion commented on app/views/games/_form.html.haml
> += form_for @game do |f|
This used to be `form_with model: game` so let's use that instead of using `form_for`. Let's convert this to use the old `form_with` so we don't get any functionality changes in this refactoring PR.

The behavior of `form_with` and `form_for` seem to have some differences based on a quick glance of the documentation:

* `form_with`: https://devdocs.io/rails~7.0/actionview/helpers/formhelper#method-i-form_with
* `form_for`: https://devdocs.io/rails~7.0/actionview/helpers/formhelper#method-i-form_for

2022-12-19 10:27 UTC, valscion commented on app/views/games/_form.html.haml
> +      %span message
I think these might not be rendering the validation messages properly. Can you try to trigger a validation error for these fields, for example by trying to submit an empty form, and checking do we see the validation errors as expected?

For `genre_id`, I think there is no way to see validation errors, but let's use the same pattern for there once we get these validation errors showing up correctly.

The validation errors also used to be inside a `div` and not a `span` so let's use the same way as we had before:

https://github.com/venuu/video-game-database-ruby/blob/7755427861cf0b821a255b236a87ad8d40674094/app/views/games/_form.html.erb#L6-L8

2022-12-19 10:27 UTC, valscion commented on app/views/games/_form.html.haml
> +  .label
The previous ERB didn't specify a class for the wrapping `<div>` elements so let's not specify a class here, either. To create a `<div>` without any CSS classes, you can use `%div`.

2022-12-19 10:27 UTC, valscion commented on app/views/games/_form.html.haml
> +    %br/
There used to be no `<br>` tags in the original ERB so let's not add those on the HAML side, either.

2022-12-19 14:14 UTC, valscion commented on app/views/genres/_form.html.haml
> += form_with model: @genre do |f|
Let's keep this PR focused on changing the games partials, so please revert this change done to genres partials. That is outside the scope of this PR.

2022-12-19 15:04 UTC, Angel-cuba commented on app/views/games/_form.html.haml
> +    %br/
In this case, maybe i deleted this tag when i change this file from .erb to .haml, but in the old code we had that
![Screenshot 2022-12-19 at 16 58 40](https://user-images.githubusercontent.com/69958243/208454664-755ef95d-71e1-4e78-88fd-9f852e14fb81.png)

and without `br` tag looks like 
<img width="229" alt="with_out_br" src="https://user-images.githubusercontent.com/69958243/208455014-5dea8de5-dbd4-4f00-aedc-bab078f2007e.png">

with the `br` tag
<img width="173" alt="brackets" src="https://user-images.githubusercontent.com/69958243/208455497-e7f9c315-a289-47f4-8666-35bf3ae536f2.png">

2022-12-19 15:26 UTC, Angel-cuba commented on app/views/games/_form.html.haml
> +      %span message
This is what we get with empty field
<img width="556" alt="empty_fileds" src="https://user-images.githubusercontent.com/69958243/208459332-c0acb967-df48-4a3f-b022-141e234dc38a.png">

`Question: `How i could avoid this brackets from the right field of each input?
<img width="173" alt="brackets" src="https://user-images.githubusercontent.com/69958243/208460465-308ec869-e277-478e-95ae-13ee09b77cfc.png">

2022-12-20 07:09 UTC, valscion commented on app/views/games/_form.html.haml
> +    %br/
Oh sorry, I didn't spot that the original did indeed have the `<br>` tags 😳 

You are right! The `%br` is indeed needed here and I was wrong.

2022-12-20 07:12 UTC, valscion commented on app/views/games/_form.html.haml
> +      %span message
Ah, you should be using `-` when looping through a collection rather than `=` as `=` outputs the result of the `game.errors.full_messages_for(:name).each` directly to the output.

So like this instead:

```haml
    - game.errors.full_messages_for(:name).each do |message| 
      %span message
```

But now there's no printing on the `message` as `%span message` should always output `<span>message</span>` instead of what the variable `message` contains.

So what you'll need is going to be something like this instead:


```haml
    - game.errors.full_messages_for(:name).each do |message| 
      %span= message
```

This way the loop isn't printed as it uses `-` instead of `=` but each item inside the loop does get printed inside the `<span>` as we are using the `=` syntax there.

2022-12-20 07:13 UTC, valscion commented on app/views/genres/_form.html.haml
> += form_with model: @genre do |f|
This is still unaddressed :point_up:

2022-12-20 07:14 UTC, valscion commented on app/views/games/_filters.html.haml
> +                = link_to genre.name, root_path(:genre=> genre.id)
The `year` query parameter is still missing.

2022-12-20 08:20 UTC, Angel-cuba commented on app/views/games/_form.html.haml
> +      %span message
Now I'm getting a weird behavior, the code looks like this:

<img width="503" alt="Screenshot 2022-12-20 at 10 11 02" src="https://user-images.githubusercontent.com/69958243/208616279-01a0a3c8-df81-48f8-af33-9976edf6bf38.png">

And only show errors messages for `year` field
![Screenshot 2022-12-20 at 10 13 45](https://user-images.githubusercontent.com/69958243/208616705-3dd3cfa1-45a6-4338-b903-3472beea6c3b.png)

To show errors for other field i have to use `=` instead of `-` and getting those annoying brackets

2022-12-20 08:24 UTC, valscion commented on app/views/games/_form.html.haml
> +      %span message
Can you check if you get the same behavior in `main` branch? Maybe it's broken there already?

2022-12-20 08:25 UTC, valscion commented on app/views/games/_form.html.haml
> +      %span message
Can you commit the changes you did so I can see what code you're running?

2022-12-20 08:57 UTC, Angel-cuba commented on app/views/games/_form.html.haml
> +      %span message
Now the issue is solved. `.each` was missing in the last changes. the code looks like:
`Before`
<img width="539" alt="before" src="https://user-images.githubusercontent.com/69958243/208624519-d9a11ffe-e396-4395-8ffb-f1bd24342c4c.png">

`After`
<img width="556" alt="after" src="https://user-images.githubusercontent.com/69958243/208624586-4626849f-de17-48c8-a3ab-7094c71ac302.png">

**Now this is what we got**
<img width="589" alt="Screenshot 2022-12-20 at 10 57 12" src="https://user-images.githubusercontent.com/69958243/208625771-848688e4-6040-41a4-88a3-45907263b4d4.png">

2022-12-20 09:00 UTC, valscion requested changes
Yess so close!

Now what's still different compared to the original is that error messages used to be wrapped in `<div>` and now they're wrapped in `<span>` tags, leading multiple validation errors to show on the same line rather than each error being shown on their own lines.

I added code suggestion on the necessary changes. If you want to accept them, please bundle them all together in one commit using the "Add suggestion to batch" button in GitHub UI.

2022-12-20 09:10 UTC, valscion approved these changes
Looks good to me now! :+1:

Regarding this:

> If you want to accept them, please bundle them all together in one commit using the "Add suggestion to batch" button in GitHub UI.

It appears that you created four distinct commits instead of using the batch operation.

2022-12-20 09:25 UTC, merged

2022-12-20 10:26 UTC, valscion commented on app/views/games/_form.html.haml
> += form_for @game do |f|
This comment was never addressed and had been marked as resolved. I failed to notice this during the next review rounds.

I created a task on the kanban board to fix this in a new PR: https://whimsical.com/use-form-with-as-requested-in-review-AdjqsBzvVj1XZbcxC7MsAZ